kind: NetworkSecurityPolicy
apiVersion: security.devops.gov.bc.ca/v1alpha1
metadata:
  name: {{ .Values.app_name }}-api-db-nsp
  labels:
    name: {{ .Values.app_name }}-api-db-nsp
    env: {{ .Values.env }}
spec:
  description: |
    Allow the api to talk to the database pod.
  source:
    - - role={{ .Values.label_api_role }}
      - app={{ .Values.app_name }}
      - env={{ .Values.env }}
  destination:
    - - role={{ .Values.label_database_role }}
      - app={{ .Values.app_name }}
      - env={{ .Values.env }}
