kind: Secret
apiVersion: v1
stringData:
  database-name: {{ .Values.kirk_pgdb_params.kirk_database_name }}
  database-password: {{ .Values.kirk_pgdb_params.kirk_database_password }}
  database-user: {{ .Values.kirk_pgdb_params.kirk_database_user }}
metadata:
  labels:
    template: postgresql-persistent-template
    app: {{ .Values.app_name }}
    env: {{ .Values.env }}
    name: {{ .Values.kirk_pgdb_secret_name }}
  name: {{ .Values.kirk_pgdb_secret_name }}
type: Opaque