name: buildBackupContainer

on: 
  push:
    branches: ['dev', 'mk_helm_cht']

#on: [workflow_dispatch]

jobs:
  build_backup:
    defaults:
      run:
        shell: bash
    name: Create Dockerfile for DB Backups Image
    runs-on: ubuntu-18.04
    outputs:
      dockerversiontag: ${{ steps.calculateImageTag.outputs.DOCKER_VERSION_TAG }}
    steps:
    # - name: Get Dockerfile for DB Backups Image
    #   run: |
    #     git clone https://github.com/BCDevOps/backup-container.git .
    #     ls -l .
    - uses: actions/checkout@v2
      name: checkout backup repo
      with:
        #repository: BCDevOps/backup-container
        repository: BCDevOps/backup-container
    - name: Verify contents of workspace
      run: |
        ls -l .

    - name: calculateImageTag
      id: calculateImageTag
      run: echo ::set-output name=DOCKER_VERSION_TAG::$(date +%Y%m%d-%H%M)
    # - name: Build and Publish Docker image
    #   uses: VaultVulp/gp-docker-action@1.1.7
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
    #     image-name: backup # Provide Docker image name
    #     image-tag: ${{ steps.calculateImageTag.outputs.DOCKER_VERSION_TAG }} # Provide Docker image tag
    #     #dockerfile: Dockerfile
    #     #build-context: ./docker

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v1
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/Dockerfile
        push: true
        tags: ${{ steps.calculateImageTag.outputs.DOCKER_VERSION_TAG }}

    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #     registry: docker.pkg.github.com
    #     repository: my-org/my-repo/my-image
    #     tag_with_ref: true


    # - name: Build and push docker image
    #   uses: docker/build-push-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     dockerfile: Dockerfile
    #     repository: my/repository
    #     tag_with_ref: true