name: buildBackupContainer

# likely want to set up as a pr event for the build eventually, once
# start moving to a full CD/CI flow
on: 
  push:
    #branches: ['dev', 'mk_helm_cht']
    branches: ['master']
    paths-ignore:
      - openshift/**
      - .vscode/**
      - docs/**
      - kirk-helm/**
      - .gitignore
      - code_of_conduct.md
      - Jenkinsfile
      - LICENSE
      - open-api.json
      - readme.md
      - src/**
      - requirements.txt

jobs:
  build_backup:
    defaults:
      run:
        shell: bash
    name: Create Dockerfile for DB Backups Image
    runs-on: ubuntu-18.04
    outputs:
      dockerversiontag: ${{ steps.calculateImageTag.outputs.DOCKER_VERSION_TAG }}
    steps:
    # - name: Get Dockerfile for DB Backups Image
    #   run: |
    #     git clone https://github.com/BCDevOps/backup-container.git .
    #     ls -l .
    - uses: actions/checkout@v2
      name: checkout backup repo
      with:
        #repository: BCDevOps/backup-container
        repository: BCDevOps/backup-container
    - name: Verify contents of workspace
      run: |
        ls -l .

    - name: calculateImageTag
      id: calculateImageTag
      run: echo ::set-output name=DOCKER_VERSION_TAG::$(date +%Y%m%d-%H%M)
      
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: bcgov/kirk/backup
        dockerfile: ./docker/Dockerfile
        path: ./docker
        tags: ${{ steps.calculateImageTag.outputs.DOCKER_VERSION_TAG }}
        push: true

        #tags: docker.pkg.github.com/${{ steps.calculateImageTag.outputs.DOCKER_VERSION_TAG }}
#docker.pkg.github.com/user/app:latest
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    #     registry: docker.pkg.github.com
    #     repository: my-org/my-repo/my-image
    #     tag_with_ref: true


    # - name: Build and push docker image
    #   uses: docker/build-push-action@v1
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     dockerfile: Dockerfile
    #     repository: my/repository
    #     tag_with_ref: true